### ISSUE TITLE
Two Problems 

### ISSUE THREAD

**Issue by lickkriptolikeicecream** [phrutis/LostCoins#21]
First, since the first release using -c all pass except says "ModMulK1order() Wrong !"

What is the issue?

Second, using many ways to create an allcoin.bin, no way works for GPU.

Process step 1: combine all address from noname except export.txt.
2. Use b58 to make .bin from text file
3. Use RMD to sort bin 
4. Use gpu -r 4 in lost coins, the new bin says illegal memory error.

Card has 12gb, bin file only 1gb total, the old allcoinbin from noname works and is larger.

Second method, also not working
1. Combine all address into same file
2. Use python h160.py to turn txt file into giant txt file with all address in h160 format
3. Use modified ethtoh160 py to convert step 2 to bin file.
4. Sort bin with RMD
5. Try it with gpu on lost coins, illegal memory error

Has anyone made successfully an allcoin.bin since noname to use in lostcoins?

Please assist,
Lick Kripto Like Ice-cream

**Comment by phrutis** [comment]
-c this check is left over from Vanitysearch, ignore the error
Not all addresses can be converted using base58. For example, bc addresses were created differently, they cannot be converted in the base58.

It is not recommended to use a database with more than 100,000,000 hashes160. The problem is not in the GPU memory, the problem is in the bloom filter. With a large base, problems can arise: False positive results, skipping, and more. Nobody has tested the correctness of the bloom filter with a large base in LostCoins yet.
Noname400 made a base for his project, during the tests it was found out that the base more than 4GB LostCoins does not accept.
