### ISSUE TITLE
Создайте функцию отмены символов priv key

### ISSUE THREAD

**Issue by Igor-cherkassy** [phrutis/LostCoins#41]
Например: мой пароль hex состоит только из букв a,b,c,d,e,f зачем мне перебирать все символы. Функция пропуска символов типа : -j 1234567890

**Comment by phrutis** [comment]
Как сделать пароль -> sha256 что бы на выходе был приват только из букв?
Продам этот способ как минимум за 100 btc )))
 
В каком режиме не нравится перебор 0-9 ? Напиши подробно зачем это нужно?

Я тоже хотел бы что бы пропускало приваты с 4 и больше одинаковыми буквами(цифрами) :)
Что согласно [гипотезе](https://github.com/phrutis/Rotor/issues/3) увеличит скорость.


256 bits of this number:
115,792,089,237,316,195,423,570,985,008,687,907,852,837,564,279,074,994,382,605,163,141,518,161,494,337

Since in Private keys (on which there were coins) there are no 4,5,7,8 identical letters in succession.
You can also speed up the speed, you need to make a filter for the same letters, numbers in succession like 1111, aaaa, cccc, bbbbb, 5555555, fffffffff ... 
If this comes across there is a pass.

Perhaps 256 bits will get a number (did not count):
985,008,687,907,852,837,564,279,074,994,382,605,163,141,518,161,494,337

Examples:
All Private keys after FFFF are invalid
**FFFF** ~~FFFF FFFF FFFF FFFF FFFF FFFF FFFE BAAE DCE6 AF48 A03B BFD2 5E8C D036 4141~~ 

All Private keys after 7777 are invalid.
**7777** ~~FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF~~

All Private keys after 1111 are invalid.
1234 **1111** ~~FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF~~

All Privare keys after AAAA are invalid.
1234 5181 1ABC AE0F F5ED 07E1 9BA5 56F3 DAE4 DAEC E5**AA AA**~~FF FFFF FFFF FFFF FFFF~~
